tiacsys/bridle

.github/workflows/qa-nightly.yml
disable:
- STM32F7: PWM loopback test fails
- STM32F7: I2C loopback test fails
=> ci: github: qa-integration no pwm and i2c tests

doc/_static/css/bridle.css, doc/_static/css/common.css
HOT FIX after release:
- adjust wrong background value (#00a9ce) to #15729d
- also adjust color for visited links (#0077c8) to #154099
=> doc: restore color scheme for Bridle docset

CMakeLists.txt, CODEOWNERS, cmake/boilerplate.cmake, cmake/gen_version_h.cmake, cmake/version.cmake, scripts/requirements-doc.txt, share/tsn-package/cmake/TsnConfig.cmake, share/zephyrbuild-package/cmake/ZephyrBuildConfig.cmake
- fix PyPi package interferences (Jinja2 and MarkupSafe reflected with Sphinx ~=3.3)
-  auto-load our new boilerplate by Zephyr
-  new "version_bridle.h" generator
=> Fixes and backports from v3.0

.github/workflows/doc-publish.yml
The actions/github-script was recently updated from v3.1.0 to v6 to catch Node 16 (f49acac1ef17b61f5945621ac99e4d7a3049a3a6), but unfortunately there were breaking changes in the API with v5:
* https://github.com/actions/github-script#breaking-changes-in-v5
* https://github.com/actions/github-script/issues/242 (comment)
Error was manifest as:
TypeError: Cannot read properties of undefined (reading 'listWorkflowRunArtifacts')
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13355:16), <anonymous>:3:38)
at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13356:12)
at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13451:26)
at Module.858 …
=> ci: github-script: cope with V5 breaking changes

doc/bridle/releases/release-notes-3.0.0.rst
* "... mos of all docsets." -> "... most of all docsets."
* "... documentat output ..." -> "... documented output ..."
issues: #54
=> doc: fix typo in release notes for v3.0.0

samples/button/CMakeLists.txt, samples/button/Kconfig, samples/button/README.rst, samples/button/prj.conf, samples/button/src/event.c, samples/button/src/init.c, samples/button/src/init.h, samples/button/src/poll.c
See #99. This adds an example application that showcases
- Using a dedicated polling thread
- Setting up GPIO interrupts
- Using the Zephyr init system to perform initialization
- Using Kconfig options to switch between modes of operation at compile time
=> Add a fancier button/led example

doc/bridle/releases/release-notes-3.5.0.rst, samples/button/src/init.c, samples/helloshell/src/main.c
As both C and C++ standards require applications running under an OS to return 'int', adapt that for Bridle to align with those standard.
Related to issue #120.
=> Fix C and C++ standard violation

.devcontainer/Dockerfile, .devcontainer/bash_completion, .devcontainer/devcontainer.json, .devcontainer/post-create.sh, .devcontainer/post-start.sh, .github/qa-igt-slz/map-nucleo_g071rb.yml, .github/workflows/qa-igt-slz.yml, CODEOWNERS
This will auto setup the whole build environment based on zephyr's docker containers. Prerequisites are:
- docker is accessable by the user without using sudo
- vscode with remote container extension is installed
Create a directory for your workspace. Go into that directory and clone the bridle repo.
Open the repo folder in vscode and select from the commands "Dev Containers: Reopen in container" (you might be prompted in the bottom right corner for that).
This will then download the docker container, install packages etc. so that you can directly start with a `west build`
=> Add devcontainer integration for vscode

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
To interactively debug CMake version 3.27 is required. As this container is based on the Zephyr SDK which is based on an Ubuntu LTS version, CMake is too old to support debugging.
Therefore we install CMake from their repository and add the CMake extension to the devcontainer file for auto-install it.
=> feat: upgrade CMake

.github/workflows/qa-integration.yml
To avoid "out of disk space" alerts and thus abandoned integration tests this split the on-container job into two new separate jobs, one for shields and one for samples.
=> ci: github: qa: split jobs into shields and samples

samples/helloshell/sample.yaml, zephyr/alt-config/drivers/can/shell/testcase.yaml
- wait longer on real hardware in our RPi4 test bed environment for CAN test suite (shell API)
- disable QEMU/ARC platforms, because of huge disk space consumption (about 2.2GB)
=> Adapt QA integration tests for time and disk space consumption

.github/workflows/doc-build.yml, .github/workflows/qa-compliance.yml, .github/workflows/qa-integration.yml
For unknown reasons, the local development host and CI is running in temporary "Error in the HTTP2 framing layer". Forcing the historical but still supported HTTP/1.1 layer seems to be a stable workaround - happened in Oct. 2023.
=> ci: git: fix "Error in the HTTP2 framing layer"

doc/_doxygen/doxyfile-bridle.in, doc/_doxygen/doxyfile-zephyr.in
Zephyr upstream now uses a new (private) CPP macro to handle nonnull attribute in internal kernel API. Thus Doxygen have to know about and strip the declarations.
=> doc: doxygen: respect macro for nonnull attribute

boards/arm/cytron_rp2040/makerpi_led_ws2812.dtsi, boards/arm/waveshare_rp2040/rp2040mini_led_ws2812.dtsi, boards/arm/waveshare_rp2040/rpipico_led_ws2812.dtsi, doc/bridle/releases/release-notes-3.6.0.rst, drivers/gpio/Kconfig.pca9554, drivers/gpio/Kconfig.pca9555
In conjunction with the latest changes at https://github.com/zephyrproject-rtos/zephyr/pull/55226, some Devicetree declarations had to be corrected. In addition, the two GPIO drivers in Bridle for PCA9554 and PCA9555 are now activated automatically.
=> Porting to latest ws2812 driver over RPi Pico PIO

modules/ubxlib/CMakeLists.txt
Resolves #187.
This PR ports upstream changes to the ubxlib builds to the substituted `CMakeLists.txt`.
To avoid such breakages in the future, we should consider using the upstream build as-is after all, despite its problems. Otherwise  we will keep having to port small changes like these manually.
=> Fix ubxlib builds

boards/shields/waveshare_pico_10dof_imu_sensor/waveshare_pico_10dof_imu_sensor.dtsi, boards/shields/waveshare_pico_environment_sensor/waveshare_pico_environment_sensor.overlay, doc/bridle/releases/release-notes-3.6.0.rst, samples/helloshell/boards/qemu_cortex_m0.conf
With the Zephyr upstream commit f5595b4b9c3bbeb44a56d27a2854a172fc5eaad6
the new (work in progress) sensing subsystem renames property 'sensor-type'
to 'sensor-types' and change the type of this required property from
'int' to an 'array' of type values.
=> Fix broken nightly QA test

boards/arm/cytron_rp2040/cytron_rp2040-makernano.dtsi, boards/arm/cytron_rp2040/cytron_rp2040-makerpi.dtsi
This is extends the two Cytron Maker boards with a set of fancy GPIO line names on DTS level. We'll need this for tutorials and better documentation.
=> boards: cytron_rp2040: add gpio-line-names

boards/arm/picoboy/core_oled.dtsi, boards/shields/rpi_pico_lcd/boards/rpipico_r3-pinctrl.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_restouch_lcd_3_5/ili9488_320x480.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_restouch_lcd_3_5/ili9488_480x320.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_restouch_lcd_3_5/rpipico_r3.dtsi, boards/shields/rpi_pico_lcd/waveshare_pico_restouch_lcd_3_5.overlay, boards/shields/waveshare_lcd/boards/waveshare_2_4_lcd/arduino_nano_r3.dtsi, boards/shields/waveshare_lcd/boards/waveshare_2_4_lcd/cytron_maker_pi_rp2040.overlay, boards/shields/waveshare_lcd/boards/waveshare_2_4_lcd/ili9341_240x320.dtsi, boards/shields/waveshare_lcd/boards/waveshare_2_4_lcd/ili9341_320x240.dtsi, boards/shields/waveshare_lcd/waveshare_2_4_lcd.overlay, doc/bridle/releases/release-notes-3.6.0.rst
- use the new upstream *MIPI DBI API* for all *ILI9xxx* based displays
- fix Devicetree structures (missing pinctrl node references)
- "The PicoBoy" doesn't need to set OLED to inverted output
=> major fixes and improvements

.github/workflows/doc-build.yml, .github/workflows/doc-publish.yml, .github/workflows/doc-remove.yml, .github/workflows/labeler.yml, .github/workflows/qa-compliance.yml, .github/workflows/qa-igt-slz.yml, .github/workflows/qa-integration.yml, .github/workflows/qa-licenses.yml, .github/workflows/qa-manifest.yml, .github/workflows/stale.yml, boards/shields/rpi_pico_lcd/boards/waveshare_pico_restouch_lcd_3_5/rpipico_r3.dtsi, doc/bridle/releases/release-notes-3.6.0.rst
With the introduction of the new MIPI DBI API on Zephyr upstream we lost this feature for a couple of weeks. Now, on upstream the [PR67089](https://github.com/zephyrproject-rtos/zephyr/pull/67089) was refreshed and the functionality is back again.
=> Reactivate the 16-bit shift register support on Waveshare Pico ResTouch LCD 3.5 shield

.devcontainer/devcontainer.json, .devcontainer/post-create.sh
This will bump the used container version for building to the latest tagged one. Also a small fix is included if the user clones the bridle repository in a folder with a name which is not "bridle".
=> Bump devcontainer version to latest tagged version

doc.nix, doc/bridle/getting_started.rst, doc/bridle/gs_nix.rst, flake.lock, flake.nix, python.nix, shell.nix, west2nix.toml
this is exactly the same PR #165 but for v3.6-branch
=> FOR v3.6: Create a nix flake for reproducible development and build environments

doc.nix, doc/bridle/getting_started.rst, doc/bridle/gs_nix.rst, flake.lock, flake.nix, python.nix, shell.nix, west2nix.toml
This PR adds a [nix flake](https://nixos.wiki/wiki/Flakes) definition, which provides as output a devshell, i.e. a development environment containing all necessary tools and libraries to work with bridle.
This (optionally) removes the dependency on any distribution packages installed via `apt` (or equivalent) apart from Nix itself, and removes the need for `pip` and `virtualenv` entirely.
To evaluate the flake, install Nix (the package manager), e.g. by `apt install nix`. Then either add `experimental-features = nix-command flakes` to `~/.config/nix/nix.conf`, or add `--experimental-features 'nix-command flakes'` to any `nix` command.
After that, simply navigate to the bridle directory, and run `nix develop` to enter the devshell environment.
As a proof-of-concept, the PR also includes a …
=> Create a nix flake for reproducible development and build environments

modules/ubxlib/CMakeLists.txt
A new common API, uTimeout [in ubxlib commit 79e808e], was added and all timeouts are routed through it. This API performs time comparisons with unsigned 32-bit arithmetic to ensure that timeouts expire correctly if they happen to cross the 32-bit wrap point, which will occur every 50 days for a millisecond tick; otherwise there were instances where a timeout could potentially get "stuck" for 25 days (the unsigned 32-bit wrap length for a millisecond tick).
See also ubxlib PR-225.
=> ubxlib: Reflect upstream new uTimeout API

doc/bridle/releases/release-notes-3.6.0.rst
Add details about the new nix flake support.
That was missing in the original v3.6.0 release notes.
=> release: fix release notes 3.6.0

flake.lock, flake.nix, python.nix, west2nix.toml
This PR brings the Bridle Nix flake in-sync with current bridle main.
In particular:
* The `zephyr` input now points towards `tiacsys/main`. When new release branches are created, their version of the flake should point toward the relevant zephyr release branch.
* The `west2nix.toml` manifest is updated to reflect a west workspace as fetched on 2024-05-16.*
* `doxmlparser` is added to the available python packages since bridle docs now require it.
* `bz` is added to the available python packages since zephyr tests now require it.
* The flake input locks are updated as of 2024-05-16.
\* It seems the `hal_espressif` zephyr module is currently subtly broken: At least one of its submodules is dangling and isn't/can't be fetched. This failure seems to be invisible to `west`, but `west2nix` …
=> Update Nix Flake

CMakeLists.txt, cmake/gen_version_h.cmake, doc/bridle/releases/release-notes-3.7.0.rst, lib/bridle/version.c, subsys/shell/modules/bridle_service.c, tests/bridle/common/src/main.c
Fixes #227.
This PR moves bridle version information into a separate header file, namespaced in the include path similarly to the Zephyr version header.
=> Separate Bridle version header from zephyr header

doc/CMakeLists.txt, dts/bindings/vendor-prefixes.txt
Within the CMake configuration, the two lists of vendor prefixes from the Zephyr and Bridle databases are now merged and transferred to the documentation creation process.
=> Use Bridle's own list of vendor prefixes

boards/shields/rpi_pico_lcd/boards/waveshare_pico_lcd_1_14/rpipico_r3.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_lcd_1_14/st7789v_135x240.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_lcd_1_14/st7789v_240x135.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_lcd_2/rpipico_r3.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_lcd_2/st7789v_240x320.dtsi, boards/shields/rpi_pico_lcd/boards/waveshare_pico_lcd_2/st7789v_320x240.dtsi, boards/shields/rpi_pico_lcd/waveshare_pico_lcd_1_14.overlay, boards/shields/rpi_pico_lcd/waveshare_pico_lcd_2.overlay, boards/waveshare/rp2040/rpigeek_lcd_st7789v.dtsi, boards/waveshare/rp2040/rpipico_lcd_st7735s.dtsi, doc/bridle/releases/release-notes-3.7.0.rst
Use the new upstream MIPI DBI driver class for ST7735R Use the new upstream MIPI DBI driver class for ST7735R.
Fixes #234
=> convert to MIPI DBI driver class

doc.nix, flake.lock, flake.nix, hook.nix, nix-bridle-hook.sh, python.nix, shell.nix, west2nix.toml
This PR:
* Updates the flake inputs
* Pulls in new packages from auxiliary repo since zephyr added more python dependencies
* Switches to new formatter following RFC 166
* Puts some boilerplate pre-build setup into a proper hook
=> Nix Flake Maintainance

.devcontainer/Dockerfile, .devcontainer/bash_completion, .devcontainer/devcontainer.json
- allow hotplug for all devices in the devcontainer
- show the whole workspace folder in the file explorer
- adds bash completion to the container
=> chore: devcontainer fixes

.github/workflows/qa-integration.yml, samples/button/sample.yaml, samples/buzzer/sample.yaml, samples/helloshell/boards/qemu_cortex_m0.conf, samples/helloshell/sample.yaml, samples/ubx_gnss/sample.yaml, samples/waveshare_pico_10dof_imu_sensor/sample.yaml, samples/waveshare_pico_environment_sensor/sample.yaml, zephyr/alt-config/drivers/display/sample.yaml, zephyr/alt-config/subsys/input/input_dump/sample.yaml
In addition to Bridle's own examples, it should also be possible to build specific Zephyr upstream examples with an alternative configuration base with the Bridle-owned specifications. For this purpose, the new tags `zephyr` and `bridle` must be introduced and respected. For the GitHub workflows, this makes the explicit naming of individual test roots unnecessary. The selection is made exclusively via the newly introduced tags.
Since Zephyr upstream PR 74435, the sensor shell commands rely on a complete integration of the sensor ASYNC API incl. RTIO subsystem with a thread pool for a dedicated RTIO work queue. This exceeds the 16KB RAM of the Cortex M0 emulator by far. The only option available at the moment is to disable the sensor shell commands.
In preparation to PR #238, #243 and #245 …
=> Repair GH pipeline: QA integration tests for samples is broken

.devcontainer/devcontainer.json
Tested by building "zephyr/samples/basic/blinky" for some boards.
=> chore: bump devcontainer version

.devcontainer/.clangd, .devcontainer/devcontainer.json, .devcontainer/post-create.sh
This will integrate clangd for better autocompletion and syntax highlighting. Assumption is made that the project build is under /workspace/build with  a compile-commands.json living inside.
=> feat: integrate clangd

boards/shields/rpi_pico_lcd/boards/waveshare_pico_restouch_lcd_3_5/rpipico_r3.dtsi, snippets/tstdrv-bldall-display-adj/tstdrv-bldall-display-adj.overlay
Use a string for the xfr-min-bits property over an integer value, as this significantly improves the readability of the MIPI DBI SPI device binding.
Related to: zephyrproject-rtos/zephyr#83565
=> drivers: mipi-dbi-spi: use string for xfr-min-bits property

samples/button/boards/cytron_maker_nano_rp2040.overlay, samples/button/boards/cytron_maker_pi_rp2040.overlay, samples/button/boards/dis_pwm_leds.dtsi, samples/button/boards/ena_gpio_leds.dtsi, samples/button/boards/picoboy_rp2040.overlay, samples/button/boards/picoboy_rp2040_color.overlay
Some boards, often RP2040-based, have only the PWM-based LEDs activated instead of the GPIO. This example requires activated GPIO LEDs in the devicetree. Special DTS overlays are now provided for this purpose:
- Cytron Maker RP2040
- The PicoBoy
=> samples: button: additional board setups

.devcontainer/devcontainer.json, .devcontainer/post-create.sh, doc/bridle/getting_started.rst, doc/bridle/gs_devcontainer.rst
This will include the updated devcontainer.json from the v4.0-branch to store all the Zephyr modules in a docker volume and add some documentation on how to actually use this devcontainer.
=> feat: update devcontainer from v4.0-branch and add documentation

doc/versions.json, submanifests/zephyr.yml
Ready for V4.1 flowing branch development, related to Zephyr's upstream 4.1 HEAD.
=> Ready for 4.1

doc/bridle/releases/release-notes-4.2.0.rst, doc/bridle/shortcuts.txt, samples/helloshell/README.rst, samples/helloshell/sample.yaml, submanifests/zephyr.yml, tests/bridle/common/testcase.yaml
- Cortex-M now requires using the cmsis_6 module. (fix #320)
- With upcoming Zephyr 4.2 the Nios2 architecture and all related board definitions will be removed.
=> bugfixes: switch to cmsis_6 and remove qemu_nios2

submanifests/zephyr.yml
Fix full featured documentation build process. Build the auto generated HW feature table w/o errors, e.g.:
- `west build -b bl604e_iot_dvk/bl604e20q2i -p -d build/bl604e_iot_dvk zephyr/samples/hello_world`
- `west build -b ai_wb2_12f/bl602c00q2i -p -d build/ai_wb2_12f zephyr/samples/hello_world`
=> manifest: support Bouffalo Lab HAL

boards/shields/loopback_test/boards/magpie_f777ni.overlay, boards/shields/loopback_test/loopback_test_tmph.overlay, doc/bridle/releases/release-notes-4.2.0.rst
Reduce fast transfer clock to max. 15 MHz, because of missing DMA setup.
As long as the board has no DMA acceleration enabled for SPI transfers the original intended clock of 50 MHz will be to fast for the new Zephyr upstream timing testcase. This would be lead to a "Very high latency" failure, the transfer takes way longer than it should.
fixes #325
=> loopback_test: tiac_magpie: reduce fast transfer clock

drivers/gpio/gpio_sc18is604.c, drivers/i2c/Kconfig.sc18is604, drivers/i2c/i2c_sc18is604.c, drivers/i2c/i2c_sc18is604.h, drivers/i2c/i2c_sc18is604_callback.c, drivers/mfd/Kconfig.sc18is604, drivers/mfd/mfd_sc18is604.c, drivers/mfd/mfd_sc18is604.h, drivers/mfd/mfd_sc18is604_transfer.c, drivers/mfd/mfd_sc18is604_transfer_async.c, include/zephyr/drivers/mfd/sc18is604.h
Adds several improvements and bugfixes for SC18IS604 type I2C controllers:
- Use static thread allocation instead of dynamic threads
- Use driver instance specific workqueue instead of the system workqueue to avoid deadlocks
- Enable device power management
The large diff is mostly caused by also running clang-format on the drivers to bring them in line with the rest of the tree. I recommend skipping the first commit on review to see only the substantial changes.
=> SC18IS604 I2C Controller: Various Improvements and Fixes

flake.lock, flake.nix, python.nix, west2nix.toml
Updates all flake inputs, including the auxiliary flake providing some required python packages. Since that flake now provides an overlay in addition to individual packages, we can simplify the way the python environment is built.
We also see much fewer invalid version constraints in the relevant `requirements.txt` now, with only two remaining: 
- ruff, where nixpkgs provides v0.11.13 while zephyr insists on v0.11.11 specifically
- sphinx-notfound-page, where nixpkgs provides v1.0.0 while zephyr asks for v1.1.0
=> Nix Flake Maintenance

.github/workflows/qa-integration.yml, doc/bridle/releases/release-notes-4.2.0.rst, drivers/mfd/sc18is604/mfd_sc18is604_emul.c
Fix #339 – an array cannot have zero size. Thus a new __ASSERT(rx_len != 0, ...) was add.
ISO 9899:2011 6.7.6.2 (https://www.iso-9899.info/n1570.html#6.7.6):
> **1 Constraints:** If the expression is a constant expression, it shall have a value greater than zero.
> **5 If the size is an expression that is not an integer constant expression:** if it occurs in a declaration at function prototype scope, it is treated as if it were replaced by *; otherwise, each time it is evaluated it shall have a value greater than zero. The size of each instance of a variable length array type does not change during its lifetime.
The above text is true both for a plain array (paragraph 1). For a variable length array (VLA), the behavior is undefined if the expression's value is less than or equal to zero …
=> Fix compile warning in SC18IS604 emulator

.devcontainer/devcontainer.json, .devcontainer/post-create.sh
The clangd path changed due to newer container version. Also the clang-format file from the zephyr project is used for formatting code.
Furthermore python packages are now installed in an virtual env which is automatically activated when a terminal is started.
=> chore[devcontainer]: minor fixups for 4.2.0

.github/workflows/qa-integration.yml, doc/_extensions/tsn_include/tsn_include.py, doc/bridle/dm_adding_code.rst, doc/bridle/dm_code_base.rst, doc/bridle/dm_managing_code.rst, doc/bridle/gs_installing.rst, doc/bridle/introduction.rst, doc/bridle/releases/release-notes-4.3.0.rst, samples/helloshell/README.rst, samples/helloshell/boards/rpi_pico_rp2040_w.conf, samples/helloshell/sample.yaml
Since Bridle also supports targets with radio modules a few specific builds may be depend on external proprietary (EULA protected) binary artefacts. West always know about this and should be used to download, clone or checkout the correct releases. Even this workflow, the how to and references to yet more upstream documentation, is now part of the Bridle documentation.
Further, for the Raspberry Pi Pico W (contains an Infineon [CYW43439](https://www.infineon.com/cms/en/product/wireless-connectivity/airoc-wi-fi-plus-bluetooth-combos/wi-fi-4-802.11n/cyw43439/) 2.4 GHz Wi-Fi/Bluetooth module that requires a binary blob) Bridle now provides a full pre-configuration and ready to use TCP/IP Network within Bridle's _"Hello SHELL"_ sample.
=> More documentation about Binary Blobs and evaluate Wi-Fi Network with RPi Pico W
